# Generated by Django 3.1.6 on 2021-02-08 21:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва команди')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('league', models.CharField(choices=[('super', 'Super'), ('high', 'High'), ('first', 'First'), ('second', 'Second'), ('student', 'Student')], default='super', max_length=7)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('W', 'Women')], default='M', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Номер футболки')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ім`я')),
                ('last_name', models.CharField(max_length=64, verbose_name='Призвіще')),
                ('middle_name', models.CharField(max_length=64, verbose_name='По-батькові')),
                ('birthday', models.DateField()),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Вага')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота в см')),
                ('attack', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота атаки')),
                ('block', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота блоку')),
                ('born_at', models.CharField(max_length=255, verbose_name='Місце народження')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.team', verbose_name='Команда')),
            ],
        ),
    ]
