# Generated by Django 3.1.6 on 2021-03-12 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=255, null=True, verbose_name='Назва команди')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('league', models.CharField(choices=[('super', 'Super'), ('high', 'High'), ('first', 'First'), ('second', 'Second'), ('student', 'Student')], default='super', max_length=7)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('W', 'Women')], default='M', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Номер футболки')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ім`я')),
                ('last_name', models.CharField(max_length=64, verbose_name='Призвіще')),
                ('middle_name', models.CharField(max_length=64, verbose_name='По-батькові')),
                ('role', models.CharField(choices=[('OS', 'Діагональний'), ('OH', 'Догравальний'), ('ST', 'Пасуючий'), ('MB', 'Центральний блокуючий'), ('LB', 'Ліберо')], default='OS', max_length=2, verbose_name='Амплуа')),
                ('birthday', models.DateField()),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Вага')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота в см')),
                ('attack', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота атаки')),
                ('block', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота блоку')),
                ('born_at', models.CharField(max_length=255, verbose_name='Місце народження')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cap', models.BooleanField(default=False)),
                ('team_name', models.CharField(max_length=255, null=True, verbose_name='Назва команди')),
                ('team_uuid', models.CharField(max_length=36, null=True, verbose_name='uuid команди')),
                ('zone', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(18)], verbose_name='Зона на майданчику')),
                ('cof_attack', models.IntegerField(default=0, verbose_name='Коефіцієнт атаки')),
                ('cof_block', models.IntegerField(default=0, verbose_name='Коефіцієнт блок')),
                ('cof_set', models.IntegerField(default=0, verbose_name='Коефіцієнт передачі')),
                ('cof_serve', models.IntegerField(default=0, verbose_name='Коефіцієнт подачі')),
                ('cof_dig', models.IntegerField(default=0, verbose_name='Коефіцієнт прийому')),
                ('cof_rc', models.IntegerField(default=0, verbose_name='Прийом ідеал')),
                ('total_attack', models.PositiveIntegerField(default=0, verbose_name='Кількість атак за матч')),
                ('total_block', models.PositiveIntegerField(default=0, verbose_name='Кількість блоків за матч')),
                ('total_set', models.PositiveIntegerField(default=0, verbose_name='Кількість передач за матч')),
                ('total_serve', models.PositiveIntegerField(default=0, verbose_name='Кількість подач за матч')),
                ('total_dig', models.PositiveIntegerField(default=0, verbose_name='Кількість прийомів за матч')),
                ('total_rc', models.PositiveIntegerField(default=0, verbose_name='Кількість ідеальних прийомів за матч')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=255, null=True, verbose_name='Назва команди')),
                ('opponent_name', models.CharField(max_length=255, null=True, verbose_name='Назва команди суперника')),
                ('set_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Номер партії')),
                ('team_points', models.IntegerField(verbose_name='Очки команди')),
                ('opponent_points', models.IntegerField(verbose_name='Очки суперників')),
                ('player_name', models.CharField(max_length=64, verbose_name='Ім`я гравця')),
                ('player_uuid', models.CharField(max_length=64, verbose_name='uuid Гравця')),
                ('action', models.CharField(choices=[('set+', 'Пас +'), ('set/', 'Пас в ігрі'), ('set-', 'Пас -'), ('serve+', 'Подача +'), ('serve/', 'Подача в ігрі'), ('serve-', 'Подача -'), ('attack+', 'Атака +'), ('attack/', 'Атака в ігрі'), ('attack-', 'Атака -'), ('rc+', 'Доводка +'), ('rc/', 'Доводка в ігрі'), ('rc-', 'Доводка -'), ('dig+', 'Прийом +'), ('dig/', 'Прийом в ігрі'), ('dig-', 'Прийом -'), ('team+', 'Забила команда'), ('team-', 'Командна помилка')], max_length=7)),
                ('action_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('first_name', models.CharField(max_length=64, verbose_name='Ім`я')),
                ('last_name', models.CharField(max_length=64, verbose_name='Призвіще')),
                ('middle_name', models.CharField(max_length=64, verbose_name='По-батькові')),
                ('birthday', models.DateField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('born_at', models.CharField(max_length=255, verbose_name='Місце народження')),
                ('phone', models.IntegerField(verbose_name='Номер телефону')),
                ('team_name', models.CharField(max_length=255, null=True, verbose_name='Назва команди')),
                ('team_uuid', models.CharField(max_length=36, null=True, verbose_name='uuid команди')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
    ]
