# Generated by Django 3.1.6 on 2021-03-13 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cof_attack',
            new_name='negative_attack',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cof_block',
            new_name='negative_block',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cof_dig',
            new_name='negative_dig',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cof_rc',
            new_name='negative_rc',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cof_serve',
            new_name='negative_serve',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='cof_set',
            new_name='negative_set',
        ),
        migrations.AddField(
            model_name='player',
            name='positive_attack',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість атак за матч'),
        ),
        migrations.AddField(
            model_name='player',
            name='positive_block',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість блоків за матч'),
        ),
        migrations.AddField(
            model_name='player',
            name='positive_dig',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість прийомів за матч'),
        ),
        migrations.AddField(
            model_name='player',
            name='positive_rc',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість ідеальних прийомів за матч'),
        ),
        migrations.AddField(
            model_name='player',
            name='positive_serve',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість подач за матч'),
        ),
        migrations.AddField(
            model_name='player',
            name='positive_set',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість передач за матч'),
        ),
        migrations.AlterField(
            model_name='game',
            name='set_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Номер партії'),
        ),
    ]
