# Generated by Django 3.1.6 on 2021-02-27 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_team_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_uuid',
            field=models.CharField(max_length=36, null=True, verbose_name='uuid команди'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ім`я')),
                ('last_name', models.CharField(max_length=64, verbose_name='Призвіще')),
                ('middle_name', models.CharField(max_length=64, verbose_name='По-батькові')),
                ('birthday', models.DateField()),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('born_at', models.CharField(max_length=255, verbose_name='Місце народження')),
                ('phone', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Номер телефону')),
                ('team_name', models.CharField(max_length=255, null=True, verbose_name='Назва команди')),
                ('team_uuid', models.CharField(max_length=36, null=True, verbose_name='uuid команди')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
    ]
