# Generated by Django 3.1.6 on 2021-03-14 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210313_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attack',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота атаки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='block',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота блоку'),
        ),
        migrations.AlterField(
            model_name='player',
            name='born_at',
            field=models.CharField(max_length=255, null=True, verbose_name='Місце народження'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Ім`я'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Висота в см'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Призвіще'),
        ),
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(max_length=64, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Номер футболки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('OS', 'Діагональний'), ('OH', 'Догравальний'), ('ST', 'Пасуючий'), ('MB', 'Центральний блокуючий'), ('LB', 'Ліберо')], default='OS', max_length=2, null=True, verbose_name='Амплуа'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Вага'),
        ),
    ]
