# Generated by Django 3.1.6 on 2021-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210227_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефону'),
        ),
    ]
