# Generated by Django 3.1.6 on 2021-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210314_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='index_attack',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт атаки'),
        ),
        migrations.AddField(
            model_name='player',
            name='index_block',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт блок'),
        ),
        migrations.AddField(
            model_name='player',
            name='index_dig',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт прийому'),
        ),
        migrations.AddField(
            model_name='player',
            name='index_rc',
            field=models.IntegerField(default=0, verbose_name='Прийом ідеал'),
        ),
        migrations.AddField(
            model_name='player',
            name='index_serve',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт подачі'),
        ),
        migrations.AddField(
            model_name='player',
            name='index_set',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт передачі'),
        ),
    ]
