# Generated by Django 3.1.6 on 2021-03-02 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Очки суперника'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва команди'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Очки команд'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(null=True, to='room.Player', verbose_name='Гравці'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_attack',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт атаки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_block',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт блок'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_dig',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт прийому'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_rc',
            field=models.IntegerField(default=0, verbose_name='Прийом ідеал'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_serve',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт подачі'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cof_set',
            field=models.IntegerField(default=0, verbose_name='Коефіцієнт передачі'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_attack',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість атак за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_block',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість блоків за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_dig',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість прийомів за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_rc',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість ідеальних прийомів за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_serve',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість подач за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_set',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість передач за матч'),
        ),
        migrations.AlterField(
            model_name='player',
            name='zone',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(18)], verbose_name='Зона на майданчику'),
        ),
    ]
