# Generated by Django 3.1.6 on 2021-03-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20210302_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='opponent',
            new_name='opponent_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team',
            new_name='team_points',
        ),
        migrations.AddField(
            model_name='game',
            name='action',
            field=models.CharField(max_length=255, null=True, verbose_name='Дія '),
        ),
        migrations.AddField(
            model_name='game',
            name='team_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва команди'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Назва команди суперника'),
        ),
    ]
