# Generated by Django 3.1.6 on 2021-03-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20210302_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
