# Generated by Django 3.1.6 on 2021-03-03 23:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0009_auto_20210302_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='action',
        ),
        migrations.RemoveField(
            model_name='game',
            name='opponent_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_points',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Очки команд')),
                ('opponent_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Очки суперника')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер партії')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.game', verbose_name='Модель гри')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='гравець')),
                ('event', models.CharField(choices=[('set+', 'Пас +'), ('set/', 'Пас в ігрі'), ('set-', 'Пас -'), ('serve+', 'Подача +'), ('serve/', 'Подача в ігрі'), ('serve-', 'Подача -'), ('attack+', 'Атака +'), ('attack/', 'Атака в ігрі'), ('attack-', 'Атака -'), ('rc+', 'Доводка +'), ('rc/', 'Доводка в ігрі'), ('rc-', 'Доводка -'), ('LB', 'Прийом +'), ('LB', 'Прийом в ігрі'), ('LB', 'Прийом -')], max_length=7, null=True, verbose_name='Подія')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.set', verbose_name='Партія')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Власник профілю')),
            ],
        ),
    ]
